### ISSUE TITLE
Install the deps with error '404 Not Found: serve@^6.4.8'

### ISSUE THREAD

**Issue by TinyChou** [rollup/rollup-starter-app#9]
tinys-MacBook-Pro:rollup-starter-app tinychou$ npm i
WARN tar ENOENT: no such file or directory, open '/Users/tinychou/Public/git_repo/rollup-starter-app/node_modules/.staging/is-extglob-3003c40a/package.json'
WARN tar ENOENT: no such file or directory, open '/Users/tinychou/Public/git_repo/rollup-starter-app/node_modules/.staging/is-extglob-3003c40a/README.md'
WARN tar ENOENT: no such file or directory, open '/Users/tinychou/Public/git_repo/rollup-starter-app/node_modules/.staging/is-extglob-3003c40a/LICENSE'
WARN tar ENOENT: no such file or directory, open '/Users/tinychou/Public/git_repo/rollup-starter-app/node_modules/.staging/is-extglob-3003c40a/index.js'
npm WARN rollup-starter-app@ No repository field.
npm WARN rollup-starter-app@ No license field.

npm ERR! code E404
npm ERR! 404 Not Found: serve@^6.4.8

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tinychou/.npm/_logs/2018-06-02T01_26_57_948Z-debug.log

**Comment by TinyChou** [comment]
when I remove the serve@6.4.8 in package.json and try npm i serve@latest     
serve@7.2.0 installed and no errors any more.

**Comment by TinyChou** [comment]
by the way,  Module ``serve`` should be in the ``devDependencies`` and not in ``dependencies``. This just private thoughts.  :)

**Comment by zoe-1** [comment]
This PR updates dependencies and works fine. #10
